"""Agentic Pipeline Builder - describe ETL in plain English, AI generates steps."""
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from typing import Optional
from app.core.deps import get_current_user, get_api_key

router = APIRouter(prefix="/pipeline", tags=["Pipeline"])

_pipelines: dict[str, list] = {}   # user_id - [pipeline]
_next_id = 1


class PipelineRequest(BaseModel):
    description: str
    api_key: str = ""


class StepRun(BaseModel):
    pipeline_id: int
    step_index: int


@router.post("/generate")
def generate_pipeline(req: PipelineRequest, api_key: str = Depends(get_api_key),
                      user: dict = Depends(get_current_user)):
    """Use LLM to generate a step-by-step ETL pipeline from plain English."""
    global _next_id
    import os, json, re
    from openai import OpenAI
    key = req.api_key or api_key or os.environ.get("OPENAI_API_KEY", "")
    if not key:
        raise HTTPException(401, "API key required")

    from app.services.data_store import get as get_df
    df = get_df(user["sub"])
    schema = ""
    if df is not None:
        schema = f"Dataset: {df.shape[0]} rows - {df.shape[1]} cols\nColumns: {list(df.columns)}"

    try:
        client = OpenAI(api_key=key)
        resp = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content":
                f"{schema}\n\nGenerate a data pipeline for: {req.description}\n\n"
                "Return a JSON array of steps. Each step: {\"name\": str, \"type\": \"clean|transform|aggregate|filter|chart|export\", \"description\": str, \"code\": str (pandas code, result in 'df')}\n"
                "Return ONLY the JSON array."}],
            temperature=0.3, max_tokens=1000,
        )
        content = re.sub(r"```(?:json)?|```", "", resp.choices[0].message.content.strip()).strip()
        steps = json.loads(content)
    except Exception as e:
        # Fallback: rule-based pipeline
        steps = _rule_based_pipeline(req.description, df)

    pipeline = {"id": _next_id, "description": req.description, "steps": steps, "status": "ready"}
    uid = user["sub"]
    if uid not in _pipelines:
        _pipelines[uid] = []
    _pipelines[uid].append(pipeline)
    _next_id += 1
    return pipeline


def _rule_based_pipeline(description: str, df) -> list:
    """Fallback rule-based pipeline generation."""
    steps = []
    desc = description.lower()
    if any(k in desc for k in ["clean", "duplicate", "null", "missing"]):
        steps.append({"name": "Clean Data", "type": "clean",
                      "description": "Remove duplicates and fill missing values",
                      "code": "df = df.drop_duplicates()\nfor col in df.select_dtypes('number').columns:\n    df[col] = df[col].fillna(df[col].median())\nresult = df"})
    if any(k in desc for k in ["filter", "where", "only"]):
        steps.append({"name": "Filter Rows", "type": "filter",
                      "description": "Filter dataset based on conditions",
                      "code": "result = df.dropna()"})
    if any(k in desc for k in ["group", "aggregate", "sum", "average", "mean"]):
        if df is not None:
            cats = df.select_dtypes("object").columns.tolist()
            nums = df.select_dtypes("number").columns.tolist()
            if cats and nums:
                steps.append({"name": "Aggregate", "type": "aggregate",
                              "description": f"Group by {cats[0]} and sum {nums[0]}",
                              "code": f"result = df.groupby('{cats[0]}')['{nums[0]}'].sum().reset_index()"})
    if any(k in desc for k in ["chart", "plot", "visualize", "graph"]):
        steps.append({"name": "Generate Chart", "type": "chart",
                      "description": "Auto-generate overview charts",
                      "code": "result = df  # Charts generated by viz agent"})
    if any(k in desc for k in ["export", "save", "download", "csv"]):
        steps.append({"name": "Export CSV", "type": "export",
                      "description": "Export processed data as CSV",
                      "code": "result = df  # Use /reports/export/csv to download"})
    if not steps:
        steps = [{"name": "Load & Preview", "type": "transform",
                  "description": "Load dataset and preview first 10 rows",
                  "code": "result = df.head(10)"}]
    return steps


@router.get("/pipelines")
def list_pipelines(user: dict = Depends(get_current_user)):
    return _pipelines.get(user["sub"], [])


@router.post("/run-step")
def run_step(req: StepRun, user: dict = Depends(get_current_user)):
    """Execute a single pipeline step against the current dataset."""
    uid = user["sub"]
    pipelines = _pipelines.get(uid, [])
    pipeline = next((p for p in pipelines if p["id"] == req.pipeline_id), None)
    if not pipeline:
        raise HTTPException(404, "Pipeline not found")
    if req.step_index >= len(pipeline["steps"]):
        raise HTTPException(422, "Step index out of range")

    step = pipeline["steps"][req.step_index]
    from app.services.data_store import get as get_df, save as save_df
    df = get_df(uid)
    if df is None:
        raise HTTPException(404, "No dataset loaded")

    try:
        import pandas as pd, numpy as np
        local = {"df": df.copy(), "pd": pd, "np": np, "result": None}
        exec(step["code"], {"__builtins__": {"len": len, "range": range, "list": list,
                                              "str": str, "int": int, "float": float,
                                              "round": round, "abs": abs, "sum": sum,
                                              "min": min, "max": max, "print": print}}, local)
        result = local.get("result", local.get("df"))
        if isinstance(result, pd.DataFrame):
            save_df(uid, result)
            return {"status": "ok", "step": step["name"], "rows": len(result),
                    "columns": len(result.columns),
                    "preview": result.head(5).replace({float("nan"): None}).to_dict("records")}
        return {"status": "ok", "step": step["name"], "result": str(result)[:500]}
    except Exception as e:
        return {"status": "error", "step": step["name"], "error": str(e)}


@router.delete("/pipelines/{pipeline_id}", status_code=204)
def delete_pipeline(pipeline_id: int, user: dict = Depends(get_current_user)):
    uid = user["sub"]
    _pipelines[uid] = [p for p in _pipelines.get(uid, []) if p["id"] != pipeline_id]
